name: Cache Dependencies
description: Caches and installs dependencies
runs:
  using: "composite"  # ✅ Must be a mapping with `using` and `steps`
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
      shell: bash  # Required for composite steps with `uses`

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
