name: Cache Dependencies
description: Caches dependencies
runs:
  using: "composite"
  steps:
    - name: Cache Dependencies
      uses: actions/cache@v4  # ✅ This is the public action
      with:
        path: node_modules
        key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
      shell: bash

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
