name: My first Angular deployment
on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Appplication checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Appplication checkout
        uses: actions/checkout@v3

      - name: Build Application
        run: npm run build --configuration production

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Application checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist

      - name: Output contents
        run: ls -R

      - name: Deploy Appplication
        uses: ./.github/actions/deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucketName: ng-learn-app
          distFiles: ./dist

          



